#!/usr/bin/ruby
# encoding: utf-8
# (c) 2011 Martin Kozák (martinkozak@martinkozak.net)

$:.push("./lib")
$:.unshift("./lib")

require "eventmachine"
require "em-batch"

class Foo
    def b1(&block)
        yield :b1
    end
    def b2(&block)
        yield :b2
    end
end

EM::run do
    q = EM::Sequencer::new(Foo::new)
    q.b1
    q.b2
    
    q.execute! do
        p q.results
    end
end
